# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174Ceg-tjJWQ1flzXeF8CWUUtmuiq3d37
"""

def dori(alomat):
 if alomat=="istima":
   return "pararsetamol"
 elif alomat=="yo`tal":
  return "azitromitsin"
 elif alomat=="bel og`rig`i":
  return "dolgit"
 elif alomat=="qorin og`rig`i":
  return "espumizan"
 elif alomat=="bosh og`rig`i":
  return "bolnol"
 elif alomat=="gripp":
  return "gripphot"
 else:
  return "shifokorga murojaat qiling"
alomat=input("belgini kiriting ")
natija=dori(alomat)
print(natija)

def mahsulot(nomi):
   if nomi=="uy noni":
    return "3500so`m"
   elif nomi=="kartoshka":
    return "6900so`m"
   elif nomi=="banan":
    return "27000so`m"
   elif nomi=="sabzi":
    return "4000so`m"
   elif nomi=="lahim go`sht":
    return "110000so`m"
   elif nomi=="pepsi":
    return "10000so`m"
   else:
    return "kassaga murojaat qiling"
nomi=input("Maxsulot nomini kiriting ")
natija=mahsulot(nomi)
print(natija)